classdef FunctionClass
   properties
      Wcet
      E
      priority_order
      upwardRank
      upwardRankBackUp
      arrivalTime
      lowerbound
      lowerBoundArray
      deadlineSlack
      relativeDeadline
      relMax
      relReq
      taskAllo
      finishTime
      deadlinePerTask
   end
end